### ISSUE TITLE
Empty project UI on Google Chrome

### ISSUE THREAD

**Issue by Lef-F** [heartexlabs/label-studio#6256] opened 2024-08-26 14:37 UTC
**Describe the bug**

Tasks not visible on a populated Label Studio project.

Tested and it affects the following browsers and versions:
- Google Chrome: `128.0.6613.85 (Official Build) (arm64)`
- Microsoft Edge: `128.0.2739.42 (Official build) (arm64)`

It does not affect:
- Vivaldi: `6.8.3381.57 (Stable channel) (arm64)`

**To Reproduce**
1. Open any populated Label Studio Project

**Expected behavior**

Given a populated project, a table of available tasks should be visible on page load.

**Screenshots**

Upon visiting the page of a populated project:
<img width="1724" alt="Screenshot 2024-08-26 at 16 25 41" src="https://github.com/user-attachments/assets/b7a949b8-d2ec-4ac6-888f-04116ccf955f">

Manually setting `height` and `width` to anything over `0px`:
<img width="1726" alt="Screenshot 2024-08-26 at 16 31 15" src="https://github.com/user-attachments/assets/5b976f74-e9d3-4355-a6ce-c837f2795bea">

**Environment (please complete the following information):**
 - OS: `MacOS Sonoma 14.6`
 - Label Studio Version: `1.13.1`

**Additional context**

Output from `/version`:
```json
{
  "release": "1.13.1",
  "label-studio-os-package": {
    "version": "1.13.1",
    "short_version": "1.13",
    "latest_version_from_pypi": null,
    "latest_version_upload_time": null,
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "ci: Build frontend",
    "commit": "d9b816a3781ee806bba50c8c5589fcdb8555a277",
    "date": "2024/08/19 19:14:23",
    "branch": "",
    "version": "1.13.1+0.gd9b816a"
  },

  "label-studio-frontend": {
    "message": "fix: LEAP-762: Fix offsets in domManager for emojis (#6135)",
    "commit": "8d8a7fce72b808d00f94cc10b49669121d186c1f",
    "date": "2024-08-01T03:08:02.000Z",
    "branch": "develop"
  },

  "dm2": {
    "message": "chore: OPTIC-866: Stylus to Sass conversion LS web/libs/datamanager/sr ...",
    "commit": "8fbedaa6fdd00338da19c258a798b8799f0cd935",
    "date": "2024-07-26T15:12:41.000Z",
    "branch": "develop"
  },

  "label-studio-converter": {
    "version": "1.0.5"
  }
}
```

**Comment by bribroder** [comment] 2024-08-26 14:52
Mostly adding my +1 to this, the last version that worked for us was Chrome 127.0.6533.122. As of 128, we have the same problem.

This affects both Windows and Mac users on amd64 and arm64.

It does not affect Firefox or Safari users on any system.

Update: 1.13.1 solved it for us

**Comment by shihao1007** [comment] 2024-08-26 15:46
Seems like the issue is gone after upgrading to 1.13.1

**Comment by nerlfield** [comment] 2024-08-26 15:53
I had the same issue. Upgrading to 1.13.1 worked for me.

**Comment by fsalmasri** [comment] 2024-08-27 06:58
I have the same issue. I updated my LS to 13.1.1. still not working on my PC Brave version 1.69.153
my other pc with brave version 1.67.134 is working

**Comment by LemonGraZ** [comment] 2024-08-27 07:27
Same problem here, upgrading to Chrome 128.0.6613.85 (Official Build) (64-bit) crashed it. Worked with previous versions. We're on Label Studio v1.8 however.

**Comment by Lef-F** [comment] 2024-08-27 07:38
FIY @makseq the output from `/version`:

```json
{
  "release": "1.13.1",
  "label-studio-os-package": {
    "version": "1.13.1",
    "short_version": "1.13",
    "latest_version_from_pypi": null,
    "latest_version_upload_time": null,
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "ci: Build frontend",
    "commit": "d9b816a3781ee806bba50c8c5589fcdb8555a277",
    "date": "2024/08/19 19:14:23",
    "branch": "",
    "version": "1.13.1+0.gd9b816a"
  },

  "label-studio-frontend": {
    "message": "fix: LEAP-762: Fix offsets in domManager for emojis (#6135)",
    "commit": "8d8a7fce72b808d00f94cc10b49669121d186c1f",
    "date": "2024-08-01T03:08:02.000Z",
    "branch": "develop"
  },

  "dm2": {
    "message": "chore: OPTIC-866: Stylus to Sass conversion LS web/libs/datamanager/sr ...",
    "commit": "8fbedaa6fdd00338da19c258a798b8799f0cd935",
    "date": "2024-07-26T15:12:41.000Z",
    "branch": "develop"
  },

  "label-studio-converter": {
    "version": "1.0.5"
  }
}
```

**Comment by makseq** [comment] 2024-08-27 09:04
Please show your browser console with errors, e.g.:
![image](https://github.com/user-attachments/assets/f95d01a8-71a0-4c46-8b76-8942b6ae5a4f)

**Comment by hlomzik** [comment] 2024-08-27 09:05
Hey, @Lef-F, could you please show us the Console? Right now you have Elements tab active and I see 4 errors

**Comment by Lef-F** [comment] 2024-08-27 09:09
Good catch @hlomzik , here's the output:

<img width="1716" alt="image" src="https://github.com/user-attachments/assets/91bdf305-d7a8-45af-b313-8b194abbdf98">

**Comment by fsalmasri** [comment] 2024-08-27 09:11
![image](https://github.com/user-attachments/assets/63d9250e-efce-484a-be36-6778dd59122a)

**Comment by MosbehBarhoumiRAI** [comment] 2024-08-27 10:11
Upgrading to 1.13.1 solved the problem !

**Comment by pasberka** [comment] 2024-08-28 01:22
the same problem + 1

**Comment by Sp00nyMan** [comment] 2024-08-28 08:09
Apparently, the problem has something to do with the recent update of Chromium to version 128, since the problem doesn't appear when I use the older version of Chrome/MS Edge with Chromium 127 or Firefox, which is not based on Chromium

**Comment by fsalmasri** [comment] 2024-08-28 08:11
I have it on MS Edge Version 128.0.2739.42

**Comment by makseq** [comment] 2024-08-28 08:14
@fsalmasri please check your ls version on this page: `<yourhost>/version`, what do you see there? 

@Sp00nyMan upgrade to LS 1.13.1.

**Comment by fsalmasri** [comment] 2024-08-28 08:16
![image](https://github.com/user-attachments/assets/27d53daa-99a9-4933-9d66-9f5cbbbdb05c)

![image](https://github.com/user-attachments/assets/68d5c151-448e-49fd-bb86-6a0bf46794c0)

**Comment by fsalmasri** [comment] 2024-08-28 08:19
It is working properly on Brave version 1.67.134

**Comment by makseq** [comment] 2024-08-28 08:29
@fsalmasri please check your ls version on this page: `<yourhost>/version`, what do you see there?

**Comment by fsalmasri** [comment] 2024-08-28 08:31
> @fsalmasri please check your ls version on this page: `<yourhost>/version`, what do you see there?

what do you mean by this? 
I attached you an image showing the version v1.13.1

**Comment by makseq** [comment] 2024-08-28 08:33
@fsalmasri I mean open this page in your browser.

**Comment by fsalmasri** [comment] 2024-08-28 08:38
![image](https://github.com/user-attachments/assets/f8a19443-d733-4b93-9711-37e862a4e045)

**Comment by makseq** [comment] 2024-08-28 08:39
Thanks, it's exactly what we need.

**Comment by makseq** [comment] 2024-08-28 11:53
In case someone wants to fix it themselves, the fix [in this commit](https://github.com/HumanSignal/label-studio/commit/cb6e4c3a08f23d78a72d8ad690b9f201b531e021).

**Comment by fsalmasri** [comment] 2024-08-28 12:36
where is this file in the docker package ?

**Comment by hlomzik** [comment] 2024-08-28 12:43
@fsalmasri in a docker it will be fully build `dm/main.css` file, so you need to find corresponding substring in this file with selector and rule and remove it. Something like
```css
<something-cell>:nth-child(var(--column-count)){padding-right:0;}
```

**Comment by fsalmasri** [comment] 2024-08-28 12:52
any idea when this version will be updated ?

**Comment by xKHUNx** [comment] 2024-08-30 12:47
I faced the same issue on 1.12 and after upgrading to 1.13.1 it works normally. 

When can we get an updated version of the Docker image?

**Comment by jombooth** [comment] 2024-09-04 19:21
Hi @xKHUNx - 1.13.1 is already available here: https://hub.docker.com/layers/heartexlabs/label-studio/1.13.1/images/sha256-20aecde3276d9cfaf6b0b0659c97d7979a1cd30e4c9f4979841dfa15dec6fc13 - closing this one since this was caused by a browser change and we've already shipped a version that fixes the problem.

**Closed as completed by jombooth** 2024-09-04 19:21 UTC
Labels: community:bug, community:reviewed

**Comment by fsalmasri** [comment] 2024-09-09 09:16
I don't know how this is considered solved. I'm using docker and version 1.13.1 and still have the same issue using chrome and MS edge. but not on firefox.

**Comment by liuy129** [comment] 2024-09-11 15:57
> In case someone wants to fix it themselves, the fix [in this commit](https://github.com/HumanSignal/label-studio/commit/cb6e4c3a08f23d78a72d8ad690b9f201b531e021).

@makseq, I am using 1.7.2dev and don't want to upgrade, and it does not seem to have that folder/file associated. is there

**Comment by YannickGibson** [comment] 2024-10-11 11:16
I can say that going from 1.11.0 to 1.13.1 solved the problem on Google Chrome. We cannot assume to use the same label studio version when we keep using the newest chrome based browser.

**Comment by PaulP49** [comment] 2024-10-30 10:14
It works for me with a new 1.13.1 instance with no existing projects. For instances upgraded from a previous version the issue still persists.

This issue should be reopened.
