### ISSUE TITLE
GCP Bucket images previews do not appear in v1.7.2 but work fine in v1.7.1

### ISSUE THREAD

**Issue by plannaAlain** [heartexlabs/label-studio#3790] opened 2023-03-07 12:53 UTC
**Describe the bug**
We've synced with a GCP Source storage successfully but image preview do not appear in v1.7.2 - downgrading back to v1.7.1 and image previews work just fine.

**To Reproduce**
1. Add a Cloud Storage source
2. Sync with Source
3. Go back to main screen

**Expected behavior**
We expect image previews to appear in v1.7.2 instead a missing image and console shows many errors reading gs://xxxx/image.jpg

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version 1.7.2

**Additional context**

**Comment by jvence** [comment] 2023-03-08 11:08
Same problem

**Comment by makseq** [comment] 2023-03-08 17:00
@jvence @plannaAlain Could you make a screenshot with an opened network panel where we can see request statuses? 
E.g.: 
![image](https://user-images.githubusercontent.com/501780/223779181-a90d128f-cfdb-42a6-a732-ca4b622a5a6d.png)

If you find any red lines there, you can open a specific request and send its body screenshot too, .e.g: 
![image](https://user-images.githubusercontent.com/501780/223779302-903f0f40-1d4a-4c95-8286-720252eea6f1.png)

**Comment by jvence** [comment] 2023-03-09 13:34
When using v1.7.2dev, the photo urls are:
gs://test-external-asset/0199544B-CC2B-4B7A-957F-DB02600BB61D.jpeg net::ERR_UNKNOWN_URL_SCHEME

When downgrading to v1.7.1, the urls is:
https://storage.googleapis.com/test-external-asset/0199544B-CC2B-4B7A-957F-DB02600BB61D.jpeg?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=xxxxt&X-Goog-Date=20230309T133017Z&X-Goog-Expires=60&X-Goog-SignedHeaders=host&X-Goog-Signature=xxxx

Somehow v1.7.2 is NOT translating the URLs appropriately even though the setup/configuration is the same on both version.

**Comment by makseq** [comment] 2023-03-11 01:15
@jvence Could you show a screenshot with page Project => Settings => Cloud storages? 
Also I need a screenshot with storage settings.

**Comment by GBPeters** [comment] 2023-03-31 13:13
Have been debugging this this as well. The issue is in https://github.com/heartexlabs/label-studio/blob/3de2ace9b53cf3ab213054a9106079aaf61796a7/label_studio/io_storages/gcs/models.py:

```python
    def _get_signing_credentials(self):
        cache_key = f'{self.google_application_credentials}'
        signing_credentials = credentials_cache.get(cache_key)
        if signing_credentials is None or signing_credentials.expired:
            signing_credentials, _ = google.auth.default(['https://www.googleapis.com/auth/cloud-platform'])
            auth_req = google.auth.transport.requests.Request()
            signing_credentials.refresh(auth_req)
            credentials_cache[cache_key] = signing_credentials
        return signing_credentials
```

Whatever is in your `google_application_credentials`, Label Studio always takes the ADC. This is the only place where the cache is set.

**Comment by makseq** [comment] 2023-03-31 15:02
Try running LS this way:
```
fflag_feat_back_dev_4166_google_project_id_11012023_long=0 label-studio
```

it seems this happened here:
https://github.com/heartexlabs/label-studio/pull/3453/files

**Comment by plannaAlain** [comment] 2023-03-31 18:21
@makseq How exactly do you run label-studio with that flag?

**Comment by nlassaux** [comment] 2023-04-02 11:58
Hi @plannaAlain, this is an env variable you need to set. You can, for example, run that command before running `label-studio` if you are in local:

`export fflag_feat_back_dev_4166_google_project_id_11012023_long=0`

Or set it in your cloud instance by finding how to set an env variable with your respective cloud provider.

**Comment by makseq** [comment] 2023-04-05 23:29
Working on this issue in the ticket LSDV-4902.

**Comment by plannaAlain** [comment] 2023-05-11 10:47
Seems this issue still exists in 1.7.5.dev - using export fflag_feat_back_dev_4166_google_project_id_11012023_long=0 does not seem to work.

**Comment by makseq** [comment] 2023-05-15 02:48
@plannaAlain @nlassaux @GBPeters @jvence could you please check how GCS works in this PR
https://github.com/heartexlabs/label-studio/pull/4189
?

**Comment by makseq** [comment] 2023-05-15 10:25
@plannaAlain @nlassaux @GBPeters @jvence One more question: do you have any Application Default Credentials (ADC)? E.g. environment variable GOOGLE_APPLICATION_CREDENTIALS is set OR gcloud auth application-default login OR your code is running on GAE or GCE instances where credentials provided by the Google App Engine or Google Compute Engine metadata server? 

This might happen because ADC settings overrides your credentials from LS Project => Cloud Storages.

**Comment by plannaAlain** [comment] 2023-05-15 10:27
We have GOOGLE_APPLICATION_CREDENTIALS set. Should we not have it set?

**Comment by plannaAlain** [comment] 2023-05-15 13:12
We tested PR #4189 with no success - 
Steps:
1- Removed the value of placeholder in label_studio/io_storages/gcs/form_layout.yml
2- export GOOGLE_APPLICATION_CREDENTIALS=keys.json
3- Tested that authentication works in project Settings | Cloud Storage | Edit (it can connect just fine)
but images urls are still: gs://...

**Comment by makseq** [comment] 2023-05-15 21:30
@plannaAlain If you reset it to empty, LS GCS should work. But also you can try my PR. It fixes this problem.

**Comment by makseq** [comment] 2023-05-16 00:34
@plannaAlain Are you sure these credentials `keys.json` are correct? If you use my PR and set google credentials inside of UI instead of environment variable, doesn't it work?

**Comment by makseq** [comment] 2023-05-17 01:07
@plannaAlain Please check my PR again, now it should work.

**Comment by makseq** [comment] 2023-05-23 17:55
PR is merged.

**Closed as completed by makseq** 2023-05-23 17:55 UTC
Labels: problem, storages, import

**Comment by patrickwasp** [comment] 2023-05-24 13:28
I updated to the latest develop image and the issue is still there. I can't load images on 1.8.1, but I can on 1.7.1.
```
{
  "release": "1.8.1dev",
  "label-studio-os-package": {
    "version": "1.8.1dev",
    "short_version": "1.8",
    "latest_version_from_pypi": null,
    "latest_version_upload_time": null,
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "fix: LSDV-5131: Fix Submit button disabled state (#4233)",
    "commit": "28b62696517b35b8870e742ce0f448491637e2bc",
    "date": "2023/05/24 10:40:53",
    "branch": "develop",
    "version": "20230524.104326-develop-28b62696"
  },

  "label-studio-frontend": {
    "message": "fix: LSDV-5131: Fix Submit button disabled state",
    "commit": "4c163b42a8695e1e55f1bec4617d45d11c50ae15",
    "branch": "master",
    "date": "2023/05/24 11:32:20"
  },
```

**Comment by patrickwasp** [comment] 2023-05-24 14:07
nevermind, it's working now. Something must have changed with CORS between 1.7.1 and later versions since I wasn't getting CORS errors before. After following the guide https://cloud.google.com/storage/docs/using-cors?cloudshell=false#gsutil to apply a CORS configuration to both source and target buckets things are working again. Thanks!

this was the CORS file I used

`cors.json`
```json
[
    {
        "origin": [
            "*"
        ],
        "responseHeader": [
            "Content-Type",
            "x-goog-resumable"
        ],
        "method": [
            "GET",
            "HEAD",
            "DELETE",
            "POST",
            "PUT"
        ],
        "maxAgeSeconds": 3600
    }
]
```

**Comment by plannaAlain** [comment] 2023-05-29 12:05
> nevermind, it's working now. Something must have changed with CORS between 1.7.1 and later versions since I wasn't getting CORS errors before. After following the guide https://cloud.google.com/storage/docs/using-cors?cloudshell=false#gsutil to apply a CORS configuration to both source and target buckets things are working again. Thanks!
> 
> this was the CORS file I used
> 
> `cors.json`
> 
> ```json
> [
>     {
>         "origin": [
>             "*"
>         ],
>         "responseHeader": [
>             "Content-Type",
>             "x-goog-resumable"
>         ],
>         "method": [
>             "GET",
>             "HEAD",
>             "DELETE",
>             "POST",
>             "PUT"
>         ],
>         "maxAgeSeconds": 3600
>     }
> ]
> ```

Tried the cors hack with no success. Testing connection works fine but nothing is synced. Could it have to do with the type of annotation files. There seems to be both .XML and JSON files in the annotation bucket. Could this be causing the issue?

**Comment by Laski** [comment] 2023-06-13 19:23
Hey! This still happens when using default credentials, but we were able to avoid it by generating a json key and loading it directly.
