### ISSUE TITLE
NER doesn't persist the normalization field

### ISSUE THREAD

**Issue by guoweis-outreach** [heartexlabs/label-studio#456] opened 2020-10-15 17:18 UTC
**Describe the bug**
In NER mode, try to provide "normazliation", it's not saved.
**To Reproduce**

**Expected behavior**
It should be saved.
**Environment (please complete the following information):**

**Additional context**

**Comment by guoweis-outreach** [comment] 2020-10-20 15:54
@hlomzik how difficult is this to be addressed? or is it something simple that someone else who is not familiar with the code base can help?

**Comment by makseq** [comment] 2020-10-20 21:31
@guoweis-outreach If you are familiar with React it can be simple. I think we will fix it in the nearest release.

**Comment by hlomzik** [comment] 2020-10-21 11:56
Oh, we've really missed it! I'll fix it soon of course. Thanks!
If you want to fix it asap — add a field to AreaMixin.js (as it should be a part of whole region, not a result) and add its serialization to Result.js

**Comment by guoweis-outreach** [comment] 2020-10-22 15:39
unfortunately, i'm not too familiar with react. When is your nearest release that will contain this fix?

**Comment by circlelychen** [comment] 2020-11-22 16:37
@hlomzik I recently bumped into this issue and found that It was reproduced in the latest release (0.8.1). Will it be possible fixed in the next scheduled release?

**Comment by niklub** [comment] 2021-01-13 13:12
Hi, @circlelychen @guoweis-outreach ! The aforementioned issue has been fixed since `label-studio==0.9.0` release (Now it acts like adding "Meta" to the region within a similar UI). Please try it out and reopen the issue if the problem persists on your side.

**Closed by niklub** 2021-01-13 13:12 UTC
Labels: issue: bug
