### ISSUE TITLE
Cannot export pre-annotated tasks

### ISSUE THREAD

**Issue by rizziemma** [heartexlabs/label-studio#889] opened 2021-05-06 09:30 UTC
**Describe the bug**
I used the API to import already annotated data in **Basic Label Studio JSON format**. It worked well as the results are actually showing on each task and they are marked as annotated. When I try to export this tasks (through API or UI), I get an empty list.
I tried to import only the data through API and annotate a few tasks through the UI, and the annotated tasks did showed up on the export. I then tried to update the annotation after importing pre-annotated tasks, but the export still fails.

**To Reproduce**
1. Import annotated data throught the API
Ex payload I used : 
`{"data": {"sentence": "SoftBank-backed OneWeb files for Chapter 11 bankruptcy plan, cuts jobs", "metadata": {}}, "annotations": [{"ground_truth": false, "result": [{"value": {"choices": ["Neutral"]}, "from_name": "sentiment", "to_name": "sentence", "type": "choices"}]}], "predictions": []}`

Label config : 
```
<View>
  <Text name="sentence" value="$sentence"/>
  <View style="box-shadow: 2px 2px 5px #999; padding: 20px; margin-top: 2em; border-radius: 5px;">
    <Header value="Choose text sentiment"/>
    <Choices name="sentiment" toName="sentence" choice="single" showInLine="true">
      <Choice value="Positive"/>
      <Choice value="Negative"/>
      <Choice value="Neutral"/>
    </Choices>
  </View>
</View>
```
2. Export data throught API or UI, results in empty data

**Expected behavior**
Pre-annotated tasks showing up in the export.

**Environment (please complete the following information):**
 - OS: linux
 - Label Studio Version == 1.0.1
 - Postgres DB in Docker 

Thanks !

**Comment by Lauler** [comment] 2021-05-12 15:33
I have the exact same issue when trying to import pre-annotated tasks as finished "annotations". 

It is possible to import them as "predictions" and then manually submit every prediction via the UI. This was my workaround. However, I think expected behavior should be that pre-annotated tasks (under the "annotations" key) show up in the export. 

Exact same environment as @rizziemma

**Comment by makseq** [comment] 2021-05-12 15:41
@rizziemma @Lauler Could check please if these annotations have skipped (cancelled) flag on the Data manager?

**Comment by makseq** [comment] 2021-05-12 17:16
@Lauler @rizziemma Thank you for your report. This is a bug and it happens because an `is_labeled` statistic wasn't re-calculated after import. I'll hope we'll fix it soon.

**Comment by deneland** [comment] 2021-05-21 19:01
Same issue here

**Comment by makseq** [comment] 2021-05-26 16:47
@deneland @Lauler @rizziemma https://github.com/heartexlabs/label-studio/pull/978 - could you check this branch please? I hope it's fixed now.

**Closed** 2021-06-09 13:19 UTC
Labels: bug

**Comment by rizziemma** [comment] 2021-06-11 15:15
I'm very sorry for the delay I don't know why I wasn't notified by your response :( I will try it soon thanks for working on it !

**Comment by Yakuho** [comment] 2023-11-03 06:10
Same issue here. @makseq 

I have run docker label-studio at version: 1.9.1

Should I change the default parameters here and restart LS docker-container as well?
https://github.com/HumanSignal/label-studio/blob/cc80fa4ab4cb747e2979a47b403e2d2e0975e880/label_studio/data_export/api.py#L78
