### ISSUE TITLE
cannot view any tasks in the project page

### ISSUE THREAD

**Issue by jet-c-21** [heartexlabs/label-studio#6291] opened 2024-09-02 14:01 UTC
**Describe the bug**
after login and clicked into the page of every projects, cannot see any of tasks

**Screenshots**
![image](https://github.com/user-attachments/assets/070202a1-cfbc-488e-b8a5-9dd0e5f3dff3)
![image](https://github.com/user-attachments/assets/8bb41f13-b618-4034-b2d4-976f0ead7ae2)

**Environment (please complete the following information):**
 - OS: linux, offical docker image: `heartexlabs/label-studio:latest`
 - Label Studio Version: `v1.12.0` (`v1.13.0` )

**Additional context**
[Bug display video](https://youtu.be/HMrjRaPjGo0?si=bhe01hW-kZ-KacZ6)

**Comment by kvkamal** [comment] 2024-09-02 17:13
Encountered the same a few days back.  Label studio v1.12.0 with my custom ml backend was working nicely until then.  Tried upgrading to v1.13.0.  I'm getting other dependency errors when running pip install requirements.txt.

**Comment by kvkamal** [comment] 2024-09-02 17:22
> Encountered the same a few days back. Label studio v1.12.0 with my custom ml backend was working nicely until then. Tried upgrading to v1.13.0. I'm getting other dependency errors when running pip install requirements.txt.

Correction... upgraded to v1.13.1

**Comment by norvancc** [comment] 2024-09-03 07:03
![WeChat5cb974d0fc2f8fe19934047bbc24df9d](https://github.com/user-attachments/assets/4a081b2a-93e7-4bc9-92de-0b6ea39ac389)
[Code in here](https://github.com/HumanSignal/dm2/blob/28adbc7a7be2ff7378c5e4c50e71517b06c8a667/src/components/MainView/GridView/GridView.styl#L14)

This syntax is not supported,The new version of Chrome may also have an issue where this code was not properly ignored, resulting in incorrect page display.Try changing var (-- column count) to 4, the page is not affected, you can temporarily use this method.

**Comment by zr520** [comment] 2024-09-04 08:03
> ![WeChat5cb974d0fc2f8fe19934047bbc24df9d](https://private-user-images.githubusercontent.com/80877747/363872824-4a081b2a-93e7-4bc9-92de-0b6ea39ac389.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzcyOTQsIm5iZiI6MTcyNTQzNjk5NCwicGF0aCI6Ii84MDg3Nzc0Ny8zNjM4NzI4MjQtNGEwODFiMmEtOTNlNy00YmM5LTkyZGUtMGI2ZWEzOWFjMzg5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA4MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWJkMjdhNjFkNzdjZDExYjQxYzQwNjllNTJiMDYzNWZlZTNjZDljYWZjMGQxZDk3MjVhZDRiMWE1NmZiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RcoDf1c9cDLVNvHkoe00RwIOuihfWYmXJFBBVLOH_5c) [Code in here](https://github.com/HumanSignal/dm2/blob/28adbc7a7be2ff7378c5e4c50e71517b06c8a667/src/components/MainView/GridView/GridView.styl#L14)
> 
> This syntax is not supported,The new version of Chrome may also have an issue where this code was not properly ignored, resulting in incorrect page display.Try changing var (-- column count) to 4, the page is not affected, you can temporarily use this method.

thanks

**Comment by jombooth** [comment] 2024-09-04 23:07
Closing as a duplicate of https://github.com/HumanSignal/label-studio/issues/6256

**Closed as completed by jombooth** 2024-09-04 23:07 UTC

**Comment by kvkamal** [comment] 2024-09-05 07:23
No Sure how to use the remedy provided.  What is dm2?  is it inside the label studio installation?  I see DataManager, but I can't navigate to the file shown.
