### ISSUE TITLE
Azure storage issue with 1.9.0 ?

### ISSUE THREAD

**Issue by pvbhanuteja** [heartexlabs/label-studio#4860] opened 2023-10-04 01:50 UTC
**Describe the bug**
Azure storage doesnt seem to work on 1.9.0. Made sure CROS settings are correct and all but still there's an issue.

**To Reproduce**
docker compose up 
version: '3.8'
services:
  label-studio:
    image: heartexlabs/label-studio:latest
    restart: always
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=some@example.com
      - LABEL_STUDIO_PASSWORD=examples
      - STORAGE_TYPE=azure
      - STORAGE_AZURE_ACCOUNT_NAME=azure-storage
      - STORAGE_AZURE_ACCOUNT_KEY=acc-key
      - STORAGE_AZURE_CONTAINER_NAME=label-studio
      - STORAGE_PERSISTENCE=1
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio
      - POSTGRE_USER=starsist-pg
      - POSTGRE_PASSWORD=pass
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=0.0.0.0
    ports:
      - 8080:8080

**Expected behavior**
Images are being uploaded to azure storage but cant retrieve or look at them after uploading. I manually checked and uploaded images that were present on storage. I also made sure CROS settings were as described in the docs.

**Comment by hogepodge** [comment] 2023-10-05 00:18
@pvbhanuteja thanks for filing your issue. Unfortunately, we're not able to reproduce the problem with the information given. To better help you, we need more information from the Label Studio logs, error from your browser, or any other information that can help us to identify the underlying issue. I'm going to close this issue, but if you're able to provide a means for us to reproduce it, we can reopen it.

**Closed as completed by hogepodge** 2023-10-05 00:18 UTC
