### ISSUE TITLE
UI Preview on Computer Vision Template not show 

### ISSUE THREAD

**Issue by KhaiNguyenDuc** [heartexlabs/label-studio#4077] opened 2023-04-21 14:39 UTC
After choosing interface in Computer vision template for labeling. The UI Preview not show anything  
See above:

![image](https://user-images.githubusercontent.com/71761537/233663803-6a1e7906-83da-4e7c-a8df-364907c71d53.png)

And whenever I label data. It show no more annotation:

![image](https://user-images.githubusercontent.com/71761537/233664182-868fa02f-d97d-4ece-833a-6847a5ae13db.png)

Can i ask if it is a bug, or its just a problem on my machine. I use it locally. Thank you in advance. 

I got the error in console:
[mobx-state-tree] Cannot resolve a reference to type 'AnonymousModel' with id: 'image#0' unambigously, there are multiple candidates: /annotationStore/root/children/1/imageEntities/0, /annotationStore/annotations/0/root/children/1/imageEntities/0, /annotationStore/annotations/0/root/children/1/imageEntities/1

**Comment by KhaiNguyenDuc** [comment] 2023-04-21 17:03
I got the error in console:
 [mobx-state-tree] Cannot resolve a reference to type 'AnonymousModel' with id: 'image#0' unambigously, there are multiple candidates: /annotationStore/root/children/1/imageEntities/0, /annotationStore/annotations/0/root/children/1/imageEntities/0, /annotationStore/annotations/0/root/children/1/imageEntities/1

**Comment by AbubakarSaad** [comment] 2023-04-29 01:29
Hello KhaiNguyenDuc,

What version of LS are you using? I tested this with 1.7.3 and it works completely fine

**Comment by tekn0ir** [comment] 2023-05-24 12:31
I get the same error on 1.7.4 open-source/community edition.

1. I am hosting files on GCS and testing it and running it in docker-compose; all works just fine.
2. When I test in GKE it stops working with that error message in the console.

What I have tested with the same results, I thought loading images that was the problem:
1. Running in normal configuration that use NGINX the "X-Accel-Redirect" header to load signed URLs.
2. Proxying the signed URLs in django via a new API route, not using NGINX in front of Label-studio.

I get the same error, so I am thinking this might be a front end problem or bug...

**Comment by AbubakarSaad** [comment] 2023-05-26 03:03
I'll try testing this on 1.7.4 but for 1.7.3 it works for me. Is it possible to show your labeling interface ?

**Comment by KhaiNguyenDuc** [comment] 2023-05-26 05:27
On my local machine, I have solved the problem by running "pip install -e . ". That seems to be an error on libs. Re-Install all libs again solved the problems

**Comment by tekn0ir** [comment] 2023-05-26 08:08
I would say this might be a duplicate of issue: #4053

Locally, this works fine with docker-compose for 1.7.2, 1.7.3, and 1.7.4. And to clarify, my setup uses a GCS, a cloud storage bucket for uploaded files even in docker-compose.

Deployed in Kubernetes on GKE with Istio versions 1.5.0 and 1.6.0 are working but not 1.7.2, 1.7.3, and 1.7.4. It fails in the browser with that particular error message on the identical versions. This makes me believe this is a front-end bug.

I have tested this with the suggested NGINX "X-Accel-Redirect" redirect proxying of signed URLs, clean pre-signed URLs with CORS set up correctly, and a custom Django proxy path internally in Label-studio without success. And that last one should be just as loading it almost as any static image.

So I think there is something wrong in the front end, as the images are loaded in the side view but not in the main annotation view. Either it's the nonstandard HTTP URL path, "/", or some route rewrite done in Istio, but at least it makes me believe this is a front-end bug.

**Comment by Justin-ZL** [comment] 2023-06-20 11:35
@KhaiNguyenDuc Have you solved it?
How was it resolved?

**Comment by tekn0ir** [comment] 2023-06-20 11:39
I solved it by migrating the database, but it was a bit of a hassle. So my problem was caused by something that changed in the database, and when I upgraded label-studio it looked like an error in the frontend.

**Comment by KhaiNguyenDuc** [comment] 2023-06-24 04:34
@cdio19 I used pip install -e . The UI work perfectly again. May be that because of library conflict. Especially the lib label-studio

**Comment by Justin-ZL** [comment] 2023-06-25 02:14
@KhaiNguyenDuc My db is MySQL8.0.What about yours?

**Comment by KhaiNguyenDuc** [comment] 2023-06-25 04:47
@cdio19 I use default Sqlite

**Comment by Justin-ZL** [comment] 2023-06-25 05:47
@tekn0ir @KhaiNguyenDuc I switched to postgresql and it's worked.

**Comment by Justin-ZL** [comment] 2023-06-25 09:53
I found the tag of Github's 1.8.0 has some problem with the JS related code in  '{label_studo_home}/label_studio/frontend/dist/react-app/'.And  I compiled it myself and replaced it, and it was resolved. Using sqlite, MySQL, and postgreSQL is all good!!!

**Closed as not planned** 2024-01-10 05:47 UTC
Labels: problem, labeling

**Comment by yuGAN6** [comment] 2024-01-18 10:22
same issue on 1.9.2 for me. No UI preview at template selection page, and forever loading at labeling. I deployed offline with docker, wondering if it affects anything. However everything works fine on 1.7.0, also locally deployed.
