### ISSUE TITLE
Data-manager failed to load when refresh the page

### ISSUE THREAD

**Issue by abhay-kum** [heartexlabs/label-studio#753] opened 2021-04-04 21:56 UTC
Data-manager failed to load the content when refreshing the page, or directly open the task in the browser. I am running the ls 1.0 with docker-compose having backed as Postgresql. sometimes it takes too much time to submit the task after doing 20-50 annotations. I have checked with the console log and found sometimes data managers return false, and sometimes label-studio return false. I am not able to understand why returning false or undefined.

 - OS: ubuntu18.04
 - Label Studio Version 1.0
 - broswer: Firefox
 
![Screenshot 2021-04-05 at 3 15 47 AM](https://user-images.githubusercontent.com/27910202/113522415-f5323d00-95bd-11eb-96ea-cb51aa2f3e55.png)

 
![Screenshot 2021-04-05 at 3 13 09 AM](https://user-images.githubusercontent.com/27910202/113522392-c4520800-95bd-11eb-8add-78d5db1bac32.png)

**Comment by makseq** [comment] 2021-04-04 22:16
@nicholasrq any ideas?

**Comment by nicholasrq** [comment] 2021-04-04 23:37
this issue should be fixed in the upcoming 1.0.1 release

**Comment by makseq** [comment] 2021-04-04 23:47
@abhay-kum Could you check Label studio 1.0.1rc1 ?

**Comment by abhay-kum** [comment] 2021-04-05 05:01
i have pull the code and run the container using docker-compose file it showing as 
![Screenshot 2021-04-05 at 9 52 10 AM](https://user-images.githubusercontent.com/27910202/113538881-fda86900-95f9-11eb-8fa7-69133b26afc2.png)

**Comment by niklub** [comment] 2021-04-05 19:39
label-studio==1.0.1 has been released (as well as the latest docker images `heartexlabs/label-studio:1.0.1` or `heartexlabs/label-studio:latest`. Please try it out and report back if the problem is still there, or close the current issue otherwise

**Comment by abhay-kum** [comment] 2021-04-06 10:34
when I am using the `docker run -it -p 8080:8080 -v 'pwd'/mydata:/label-studio/data heartexlabs/label-studio:latest` it is working fine , but when i try to run using docker-compose-file the static content not able to fetched.

![Screenshot 2021-04-06 at 3 59 38 PM](https://user-images.githubusercontent.com/27910202/113697985-9a016700-96f1-11eb-917f-d16ccbfa41ec.png)

**Comment by niklub** [comment] 2021-04-08 15:10
Hi, @abhay-kum ! Have you set `LABEL_STUDIO_HOST` variable to your custom hostname within docker-compose.yml ?

**Comment by niklub** [comment] 2021-04-08 15:26
This [PR](https://github.com/heartexlabs/label-studio/pull/775) also let you avoid specifying hostname explicitly

**Comment by abhay-kum** [comment] 2021-04-09 02:55
@niklub all issue has been resolved, so I am closing it thanks everyone for your support

**Closed** 2021-04-09 02:55 UTC
Labels: issue: bug
