### ISSUE TITLE
Add support for DICOM images

### ISSUE THREAD

**Issue by kirbyju** [heartexlabs/label-studio#6155] opened 2024-07-31 17:19 UTC
**Is your feature request related to a problem? Please describe.**
Annotating medical images in DICOM format to identify specific regions of interest (e.g. a particular organ or location of a tumor) is an extremely common task.  However, these DICOM data contain a huge wealth of metadata that are often critical to understanding and analyzing them later.  In order to use these kinds of data one must first convert the DICOM to a format you support, which discards all of this information or requires you to keep it in a separate location/database.  Then, after the annotations are generated, one must go through a tedious process of regenerating properly formatted DICOM data with all of that metadata.

**Describe the solution you'd like**
Add native support for reading DICOM images and, ideally, also support for DICOM annotation formats (SEG, RTSTRUCT, SR) to capture the output labels.

**Comment by jombooth** [comment] 2024-07-31 22:17
Hi, thank you for opening this issue! We've gotten this request a number of times; the challenging part from our side is in large part that DICOM images are often very very large in size, and we'd need to be very strategic about how we display those in the browser and support annotation of them. I'm going to close this one as a duplicate of https://github.com/HumanSignal/label-studio/issues/1663, but we appreciate the interest and definitely recognize the community demand for DICOM labeling!

**Closed as completed by jombooth** 2024-07-31 22:17 UTC
