### ISSUE TITLE
First word is not highlighted when annotating texts

### ISSUE THREAD

**Issue by sharkzeeh** [heartexlabs/label-studio#1210] opened 2021-07-23 12:48 UTC
**Describe the bug**

When I want to put labels on text data for the NER NLP task including the first word of the sentence

**To Reproduce**
1. Start annotating some text
3. Select a label one wants to annotate the first word (or an entire sentence including the first word)
4. The label appears in the "Regions" section (on the right by default), but the area that was selected is not highlighted in the text

**Expected behavior**

Labeling the first word (or the whole sentence with the first word) should also highlight the text.

**Screenshots**

![image](https://user-images.githubusercontent.com/36710035/126782919-b35c0776-2c85-43cc-b577-eaa1f87096cf.png)

**Comment by uklft** [comment] 2021-07-23 15:04
Possible duplicate of https://github.com/heartexlabs/label-studio/issues/1208

**Comment by sharkzeeh** [comment] 2021-07-26 11:43
@uklft yes, sure, my issues seems the same as yours

**Comment by makseq** [comment] 2021-07-26 16:11
@uklft @sharkzeeh could you check the latest LS master branch? I hope it's fixed there.

**Comment by uklft** [comment] 2021-07-27 08:27
@makseq For me this issue is sadly not resolved with the latest master branch. Same problem and same error messages in the js-logs:
![Screenshot from 2021-07-27 10-26-43](https://user-images.githubusercontent.com/35134759/127122154-442f4efa-df6a-4756-bab5-cb1bf3f1ceab.png)

**Comment by sharkzeeh** [comment] 2021-07-27 10:01
> @uklft @sharkzeeh could you check the latest LS master branch? I hope it's fixed there.

We are also using the latest version from the master branch

**Comment by 1ytic** [comment] 2021-07-29 09:53
I have the same issue. If the span starts on a new line, it is not highlighted.

**Comment by makseq** [comment] 2021-08-01 22:33
@sharkzeeh @uklft @1ytic 
https://github.com/heartexlabs/label-studio/pull/1234

Could you install LS from this branch please (fix/highlight-ls) and check this problem again?

**Comment by uklft** [comment] 2021-08-02 07:45
Hey @makseq, it seems to work for me. Thank you so much for fixing it that fast!

**Comment by lluissalord** [comment] 2021-08-03 15:35
Do we have any update on when #1234 is expected to be merged to master?

**Comment by sharkzeeh** [comment] 2021-08-03 18:37
@lluissalord  @makseq 
Hi! Sorry, I didn't answer yesterday. I've tried it - works as expected now! Thanks

**Comment by inzomiac** [comment] 2021-08-09 08:08
tried this fix by using git checkout only... I still encounter this issue :(

**Comment by inzomiac** [comment] 2021-08-09 08:10
See image for reference
![image](https://user-images.githubusercontent.com/16258456/128676572-2c8769f8-f9d3-40ad-a595-05cd2db63f6b.png)

**Comment by inzomiac** [comment] 2021-08-09 08:10
![image](https://user-images.githubusercontent.com/16258456/128676640-448cf767-de54-47b7-9771-4d5f519d1940.png)
using branch fix/highlight-lsf

**Comment by inzomiac** [comment] 2021-08-09 08:19
ok seems that when you download the entire source code from this branch it fixes the issue.
Hope you could push this fix in master 👍 Thanks... Kudos to the one who fixed this

**Closed** 2021-09-07 17:19 UTC
Labels: bug, Text
