### ISSUE TITLE
Segmentation Brush Changing Size when pressing submit

### ISSUE THREAD

**Issue by mcombalia** [heartexlabs/label-studio#374] opened 2020-07-22 13:38 UTC
Before pressing udpate:

<img width="786" alt="Captura de pantalla 2020-07-22 a las 15 36 49" src="https://user-images.githubusercontent.com/50626537/88183118-56350300-cc31-11ea-8c07-2a015af5bdd2.png">

After Pressing update:

<img width="794" alt="Captura de pantalla 2020-07-22 a las 15 36 58" src="https://user-images.githubusercontent.com/50626537/88183134-5af9b700-cc31-11ea-8cba-443f24557e6a.png">

**Comment by makseq** [comment] 2020-07-22 14:00
Can you show your label config? Do you use LS v0.7.3?

**Comment by mcombalia** [comment] 2020-07-22 14:02
Label config:

<View>

  <Header value="Select label and start to click on image"></Header>
  <Image name="image" value="$image" />
  
  <Choices name="capa" toName="image" choice="multiple">
    <Choice value="Epidermis"></Choice>
    <Choice value="Union"></Choice>
    <Choice value="Dermis"></Choice>
  </Choices>
  
  <BrushLabels name="segmentation" toName="image">
    <Label value="Lesion" />
    <Label value="Epidermis" />
    <Label value="Union"/>
    <Label value="Dermis"/>
  </BrushLabels>

</View>


I am using the version from docker, installed this morning.

**Comment by makseq** [comment] 2020-07-22 14:36
What browser do you use? (I still can't reproduce this issue)

**Comment by makseq** [comment] 2020-07-24 22:22
https://github.com/heartexlabs/label-studio/issues/276

**Comment by makseq** [comment] 2020-08-08 00:19
@mcombalia Please, check 0.7.4rc2: 

```
pip uninstall label-studio
pip install label-studio==0.7.4rc2
```

**Comment by makseq** [comment] 2020-08-13 21:02
Fixed in https://github.com/heartexlabs/label-studio/releases/tag/v0.7.4

**Closed by makseq** 2020-08-13 21:02 UTC
Labels: issue: bug
