### ISSUE TITLE
Previously Labeled Images No Longer Show Up Under Project

### ISSUE THREAD

**Issue by JTMarsh556** [heartexlabs/label-studio#6353] opened 2024-09-09 18:33 UTC
I can no view the images that I labeled.  They export fine.  I am rather new to this tool so I may be making an error but I have spent a lot of time trying to figure this out so I am seeking help.

The best I can tell is that when I go to the project I should see a table with the columns but my screen is blank.  It has been a couple of weeks but it was here the last time I used the tool.  Now none of my projects are displaying project information.  

I have attached a screenshot of what I am seeing.  Any direction on this would be greatly appreciated.  

![Screenshot 2024-09-09 133147](https://github.com/user-attachments/assets/1848e987-49ba-4a2d-ab2a-876ba2a73485)

**Comment by eylongu** [comment] 2024-09-10 07:25
Same here

Seems like a React exception, the server does return the json/data

**Comment by eylongu** [comment] 2024-09-10 07:37
https://github.com/HumanSignal/label-studio/issues/6182

Update label-studio version (to 1.13) seemed to work for Chrome

**Comment by tienldbnk** [comment] 2024-09-10 13:09
> #6182
> 
> Cập nhật phiên bản label-studio (lên 1.13) có vẻ hoạt động với Chrome

I run the original source code using the command "python label_studio/manage.py runserver" it seems like it is required to start the FrontEnd source

**Comment by withwz** [comment] 2024-09-11 02:57
same, I switched to safari browser can do

**Comment by tienldbnk** [comment] 2024-09-11 06:06
> #6182
> 
> Update label-studio version (to 1.13) seemed to work for Chrome

@eylongu  help me

**Comment by vidixha** [comment] 2024-09-12 05:22
are you building from docker - compose? update the label studio docker image to latest version and it will solve this issue

**Comment by tienldbnk** [comment] 2024-09-12 06:14
> are you building from docker - compose? update the label studio docker image to latest version and it will solve this issue

No , I run source code local by command "python label_studio/manage.py runserver"

**Comment by tienldbnk** [comment] 2024-09-12 06:17
> are you building from docker - compose? update the label studio docker image to latest version and it will solve this issue

It started to fail when merging this commit: "https://github.com/HumanSignal/label-studio/commit/c5696cd87c585322d3bdc378aa3f52e566624e3d" , and forced me to run the FrontEnd source which I didn't need before.

**Comment by jombooth** [comment] 2024-09-17 17:14
Hi, this looks like a duplicate of the following issue: https://github.com/HumanSignal/label-studio/issues/6256

**Closed as completed by jombooth** 2024-09-17 17:14 UTC
Labels: community:reviewed
