### ISSUE TITLE
Labelling tasks hang with untraceable error

### ISSUE THREAD

**Issue by ljvmiranda921** [heartexlabs/label-studio#248] opened 2020-04-03 05:36 UTC
**Describe the bug**

Hi, I am trying to make a Sentence Text Similarity (STS) task using Label Studio. The idea is that given two sentences, we rate a score between 1 to 5. 

I was able to configure both `config.xml` and `tasks.csv` properly, but when it comes to the actual labelling, it's just stuck at the loading screen.

Can you please guide me on anything I might have missed?

**To Reproduce**

Minimal `config.xml`:

```xml
<View>
  <Text name="sentences" value="$pair" />
  <Rating name="rating" toName="sentences" maxRating="5" icon="star" size="medium" />
</View>
```

Minimal `tasks.csv` (I load this via the UI):

```csv
pair
The sky is dark tonight. It is a bit dark.
News reports say that the weather will be stormy. The dog is cute.
Label studio is awesome! Label studio is cool!
```

Logs. There's a `501` error in the POST request, and I'm not sure why it's happening

```sh
[2020-04-03 13:28:47,288] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:47] "GET /static/editor/js/main.f4f4d9ba.js HTTP/1.1" 304 -
[2020-04-03 13:28:47,289] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:47] "GET /static/js/lsb.js HTTP/1.1" 304 -
[2020-04-03 13:28:48,033] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:48] "GET /static/images/ls_logo.png HTTP/1.1" 304 -
[2020-04-03 13:28:48,036] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:48] "GET /static/images/slack.png HTTP/1.1" 304 -
[2020-04-03 13:28:48,038] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:48] "GET /static/images/github.svg HTTP/1.1" 304 -
[2020-04-03 13:28:48,915] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:48] "GET /api/projects/1/next/ HTTP/1.1" 200 -
[2020-04-03 13:28:55,799] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:55] "POST /api/tasks/0/completions/ HTTP/1.1" 501 -
[2020-04-03 13:28:56,692] [werkzeug] [INFO] 127.0.0.1 - - [03/Apr/2020 13:28:56] "GET /api/projects/1/next/ HTTP/1.1" 200 -
```

**Expected behavior**
I expect that whenever I click the Submit button, it registers as a completion. So far it's just stuck in the loading screen

**Screenshots**

It usually hangs here
![bug_report_00](https://user-images.githubusercontent.com/12949683/78327605-dca8d480-75af-11ea-8b6c-6577e620435a.png)

This also shows up when I try the web app demo
![in_webapp](https://user-images.githubusercontent.com/12949683/78328997-1b8c5980-75b3-11ea-91e1-0539336d03f5.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 5.1

**Additional context**

**Comment by deppp** [comment] 2020-04-07 03:10
@ljvmiranda921 Thanks for the thorough bug report, I can reproduce and the error seems to be with the Rating component. Looks like it was not updated with the latest release. We're planning to fix that with the 0.6.0 in the next couple of weeks. For now, you can simulate the same functionality using the Chocies tag. Feel free to ping me in Slack meanwhile if you need additional help with that.

**Comment by ljvmiranda921** [comment] 2020-04-07 03:53
Hi @deppp thanks a lot for this! Ok, for now, I'll use the Choices tag instead. 
I appreciate the prompt response. Let me know if I should close this Issue or if you'll still use this as a reference for the bugfix.

**Comment by makseq** [comment] 2020-04-12 20:21
Resolved in the last master of LS.

**Closed by makseq** 2020-04-12 20:21 UTC
Labels: issue: bug
