### ISSUE TITLE
ML Backend Error - Using Example Docker

### ISSUE THREAD

**Issue by lv185039** [heartexlabs/label-studio#1731] opened 2021-11-12 06:57 UTC
**Describe the bug**
When utilizing the example provided Docker ML backend I am able to spin-up the docker and the logs show operational status.  When I attempt to enter the URL for the backend into the label-studio "Machine Learning" menu I am returned with an error
`Successfully connected to http://192.168.0.9:9090 but it doesn't look like a valid ML backend. Reason: 500 Server Error: INTERNAL SERVER ERROR for url: http://192.168.0.9:9090/setup.
Check the ML backend server console logs to check the status. There might be
something wrong with your model or it might be incompatible with the current labeling configuration.`

**To Reproduce**
1. Go to the label-studio UI and open settings for project
2. Click on 'Machine Learning'
3. Scroll down to 'Enter the backend details' 
4. See error as Validation Error when clicking Save

**Expected behavior**
Expected behavior would be a functional use case scenario.

**Environment (please complete the following information):**
 - OS: Win 10
 - Docker-image (official) for ML Backend
 - Label Studio Version Release 1.3

**Additional context**
I was able to find this in the _label-studio-ml-backend\label_studio_ml\examples\simple_text_classifier\logs\uwsgi.log_:

```
[pid: 29|app: 0|req: 6/6] 172.18.0.1 () {34 vars in 479 bytes} [Fri Nov 12 06:02:45 2021] POST /setup => generated 737 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 91 bytes (1 switches on core 0)
invalid HTTP request size (max 4096)...skip

[2021-11-12 06:07:21,785] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 481, in fetch
    model = cls.model_class(label_config=label_config, **kwargs)
  File "./simple_text_classifier.py", line 30, in __init__
    assert self.info['type'] == 'Choices'
AssertionError

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 49, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 481, in fetch
    model = cls.model_class(label_config=label_config, **kwargs)
  File "./simple_text_classifier.py", line 30, in __init__
    assert self.info['type'] == 'Choices'
AssertionError

```

**Comment by makseq** [comment] 2021-11-12 22:58
@lv185039 What is your labeling config? I think you have not only choices there and it's not supported with this simple_text_clasifier ML backend.

**Comment by hemangjoshi37a** [comment] 2022-09-09 14:17
Hi everyone,
I have found the solution. Actylly the problem is with the configuration with the type of labeling and the type of ML example you are loading. You have to make same type of labeling as the ML backend you are loading for the job or otherwise it will give error.
https://hjlabs.in

**Comment by makseq** [comment] 2022-09-13 23:13
closed as unanswered.

**Closed** 2022-09-13 23:13 UTC
Labels: ML, backend

**Comment by sammar30** [comment] 2022-11-24 16:01
> Could you please explain more? how did you fix this problem?

**Comment by makseq** [comment] 2022-11-29 02:45
Try the latest ml backend docker versions, it should work there.

**Comment by sammar30** [comment] 2022-11-29 02:47
thanks for your reply!

**Comment by AnasAr96** [comment] 2023-01-02 16:11
i don't get it :( how can I solve the it?

**Comment by makseq** [comment] 2023-01-06 13:53
Just upgrade everything to the latest versions.

**Comment by AnasAr96** [comment] 2023-01-06 16:54
Solved by setting the right labels to the label-studio frontend 
Sometimes you have to w8 until the backend has loaded the Machine Learning-Model
