### ISSUE TITLE
Serving an Image File from a Static Server Gives "There was an issue loading URL from $image value" error

### ISSUE THREAD

**Issue by wpm** [heartexlabs/label-studio#5252] opened 2024-01-07 02:39 UTC
**Describe the bug**
I am trying to create a bounding box image annotation project where the images are served from a static file server. The image file is served, but I get a "There was an issue loading URL from $image value" error in Label Studio. It looks like this.

<img width="1293" alt="label-studio-error" src="https://github.com/HumanSignal/label-studio/assets/141456/969eb87c-e0cc-4aa2-8ad1-40e0509fd5bc">

I can't get Label Studio to do the labeling task.

**To Reproduce**
1. Install Label Studio and a static file server using the following `docker-compose.yml` file.
```yaml
version: "3.8"

services:
  label-studio:
    container_name: label-studio
    image: heartexlabs/label-studio:latest
    ports:
      - "8080:8080"
    volumes:
      - label-studio:/label-studio/data

  image-server:
    container_name: image-server
    image: joseluisq/static-web-server:2.24.0-alpine
    environment:
      - SERVER_CORS_ALLOW_ORIGINS=*
      - SERVER_DIRECTORY_LISTING=true
      - SERVER_DIRECTORY_LISTING_ORDER=0
      - SERVER_HEALTH=true
    ports:
      - "8787:80"
    volumes:
      - image-server:/public

volumes:
  image-server:
  label-studio:
```
2. Run `docker compose up`.
3. Copy an image file called `my-image.png` to the `/public` directory on the image server, the root of its file share.
4. Verify that the image file is visible at http://localhost:8787/my-image.png.
5. Create a Label Studio project with a labeling configuration identical to the [example bounding box labeling configuration](https://labelstud.io/templates/image_bbox#Labeling-Configuration) in the Label Studio documentation.
```html
<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="Car" background="blue"/>
  </RectangleLabels>
</View>
```
7. Import project data by uploading a CSV file that has the following contents:
```csv
image
http://localhost:8787/my-image.png
```
8. When you try to label the task you see the error.

Because the error message mentions CORS I tried

1. Removing the `SERVER_CORS_ALLOW_ORIGINS` environment variable on the static server.
2. Setting the the `SERVER_CORS_ALLOW_ORIGINS` environment variable in the static server to `http://localhost:8787`.

In both these cases I saw the same error as before.

**Expected behavior**
I expect the image to be displayed in the Labeling UI.

**Environment:**
 - OS: Mac OS 14.2.1
 - Label Studio Version 1.10.0

**Comment by wpm** [comment] 2024-01-07 02:47
I am seeing this in Chrome 120.0.6099.129 but not Safari 17.2.1. Maybe the browsers handle CORS differently?

**Comment by lackray** [comment] 2024-01-09 03:27
the image is too large to render. you can rerender the width and height of image loading in the `ImageView.js`.
when the image got large enough,like 300MB+,all the browsers will fail to render.but firefox can still render,slowly though.

**Comment by makseq** [comment] 2024-01-09 18:39
If you run LS as https, you have to use https for your hosting too - http**s**://localhost:8787/my-image.png

**Comment by hogepodge** [comment] 2024-01-11 01:39
@wpm using the docker-compose file you provided, I couldn't reproduce the error, and had no issues with loading images into the Label Studio interface. I suspect that there's a local misconfiguration.

I copied the images into the public volume, then uploaded the image tasks as a list of direct URLs to each file (for example)

```
image
http://localhost:8787/image-server/346491d7c00ea717070a333387fe02a72ef47b38-880x793_4r2Q2.jpg   
http://localhost:8787/image-server/8baqv4.jpg   
http://localhost:8787/image-server/8belxy.jpg   
http://localhost:8787/image-server/8bxmc5.jpg
```

Since I can't reproduce the issue, I'm going to close this, and we can discuss it further in the community slack channel. Thanks for reaching out.

**Closed as completed by hogepodge** 2024-01-11 01:39 UTC
Labels: community:reviewed
