### ISSUE TITLE
Cannot remove model

### ISSUE THREAD

**Issue by andreaferretti** [heartexlabs/label-studio#425] opened 2020-09-17 10:29 UTC
In the model page, the X button to disconnect the model does not work.

**To Reproduce**
1. Create a ML backend
1. Go to model page
2. Add a ML backend
3. Click the X button on the connected backend
4. Confirm that you want to delete the model
5. The model is still there

**Expected behavior**
The model should be removed.

Even better, the slider on the bottom of the model card could be used to disconnect the model without removing it altogether -- right now, it is unfunctional.

**Screenshots**
<img width="1371" alt="model" src="https://user-images.githubusercontent.com/1962818/93459028-68ee5000-f8e1-11ea-97ae-c9edcfaa8967.png">

**Comment by fromnorthpole** [comment] 2020-09-24 11:52
@andreaferretti can't reproduce that issue. Can you check whether there are some error logs in the server console while deleting the ML backend?

**Comment by andreaferretti** [comment] 2020-09-24 13:53
No errors in the console. I noticed that it only happens in Firefox. In Chrome, there is no issue. (I am on MacOS if it helps)

**Comment by kathoum** [comment] 2020-09-28 08:59
Related: pull request #439

**Comment by makseq** [comment] 2020-09-28 13:56
Fixed in release 0.7.5.

**Closed by makseq** 2020-09-28 13:56 UTC
Labels: issue: bug
